export const Questions = [
  // Chapitre 1: Introduction à la Sécurité des Systèmes d'information
  {
    number: 1,
    type: "qcu",
    question: "Selon les normes ISO/IEC, quelles sont les principales ressources d'un système d'information ?",
    options: [
      "A. Physiques, humaines, matérielles, logicielles et organisationnelles",
      "B. Matérielles, logicielles et financières uniquement",
      "C. Humaines, techniques et budgétaires",
      "D. Serveurs, applications et utilisateurs",
    ],
    answers: ["A"],
  },
  {
    number: 2,
    type: "qcu",
    question: "Quelle fonctionnalité d'un système d'information consiste à transformer les données en informations exploitables ?",
    options: [
      "A. Collecte",
      "B. Stockage",
      "C. Traitement",
      "D. Diffusion",
    ],
    answers: ["C"],
  },
  {
    number: 3,
    type: "qcu",
    question: "Quels sont les trois piliers essentiels de la sécurité des systèmes d'information ?",
    options: [
      "A. Confidentialité, Intégrité, Disponibilité",
      "B. Protection, Détection, Réaction",
      "C. Prévention, Correction, Supervision",
      "D. Authentification, Autorisation, Audit",
    ],
    answers: ["A"],
  },
  {
    number: 4,
    type: "qcu",
    question: "Que désigne la traçabilité dans le contexte de la sécurité des SI ?",
    options: [
      "A. La vitesse de transmission des données",
      "B. La capacité à reconstituer l'histoire d'une opération depuis sa création",
      "C. Le chemin physique des câbles réseau",
      "D. La localisation géographique des serveurs",
    ],
    answers: ["B"],
  },
  {
    number: 5,
    type: "qcu",
    question: "Au Maroc, quelle loi impose aux opérateurs d'infrastructures d'importance vitale de mettre en place des dispositifs de sécurité conformes ?",
    options: [
      "A. Loi 09-08",
      "B. Loi 05-20",
      "C. Loi 53-05",
      "D. Loi 31-08",
    ],
    answers: ["B"],
  },
  {
    number: 6,
    type: "qcu",
    question: "Quel organisme marocain est chargé de la mise en œuvre et du suivi de la loi relative à la cybersécurité ?",
    options: [
      "A. ANRT",
      "B. DGSSI",
      "C. CERT-MA",
      "D. CNSS",
    ],
    answers: ["B"],
  },
  {
    number: 7,
    type: "qcu",
    question: "Parmi les problèmes fondamentaux de sécurité, lequel désigne l'indisponibilité d'une ressource ou d'un service ?",
    options: [
      "A. L'interception",
      "B. La modification",
      "C. L'interruption",
      "D. La fabrication",
    ],
    answers: ["C"],
  },
  {
    number: 8,
    type: "qcu",
    question: "Quel problème de sécurité correspond à l'accès illégitime à une information par un tiers non autorisé ?",
    options: [
      "A. L'interruption",
      "B. L'interception",
      "C. La modification",
      "D. La fabrication",
    ],
    answers: ["B"],
  },
  {
    number: 9,
    type: "qcu",
    question: "La fabrication, en tant que problème de sécurité, désigne :",
    options: [
      "A. La création de matériel informatique",
      "B. L'introduction de fausses informations dans le système",
      "C. La construction d'infrastructures réseau",
      "D. Le développement d'applications",
    ],
    answers: ["B"],
  },
  {
    number: 10,
    type: "qcu",
    question: "Dans un système d'information bancaire, que représentent les DAB/GAB ?",
    options: [
      "A. Des ressources humaines",
      "B. Des ressources physiques",
      "C. Des ressources logicielles",
      "D. Des ressources organisationnelles",
    ],
    answers: ["B"],
  },
  {
    number: 11,
    type: "qcu",
    question: "Quel principe limite les risques d'abus en n'accordant que les permissions strictement nécessaires ?",
    options: [
      "A. Principe de défense en profondeur",
      "B. Principe du moindre privilège",
      "C. Principe de séparation des tâches",
      "D. Principe de redondance",
    ],
    answers: ["B"],
  },
  {
    number: 12,
    type: "qcu",
    question: "La sécurité physique se décline en deux grands volets selon ISO/IEC 27002 :",
    options: [
      "A. Interne et externe",
      "B. Sécurité des zones et sécurité des équipements",
      "C. Active et passive",
      "D. Préventive et corrective",
    ],
    answers: ["B"],
  },
  {
    number: 13,
    type: "qcu",
    question: "Quel domaine de sécurité s'intéresse à la gestion quotidienne du système d'information ?",
    options: [
      "A. Sécurité physique",
      "B. Sécurité logique",
      "C. Sécurité de l'exploitation",
      "D. Sécurité applicative",
    ],
    answers: ["C"],
  },
  {
    number: 14,
    type: "qcu",
    question: "Quels protocoles sont recommandés pour protéger la confidentialité des communications ?",
    options: [
      "A. HTTP, FTP, Telnet",
      "B. TLS, IPsec, SSH",
      "C. SMTP, POP3, IMAP",
      "D. DNS, DHCP, ARP",
    ],
    answers: ["B"],
  },
  {
    number: 15,
    type: "qcu",
    question: "La segmentation des réseaux sensibles vise principalement à :",
    options: [
      "A. Augmenter la vitesse du réseau",
      "B. Limiter la propagation d'incidents et compartimenter le réseau",
      "C. Réduire les coûts",
      "D. Faciliter l'administration",
    ],
    answers: ["B"],
  },
  {
    number: 16,
    type: "qcu",
    question: "Parmi les secteurs suivants, lequel est considéré comme infrastructure d'importance vitale au Maroc ?",
    options: [
      "A. Restaurants et hôtels uniquement",
      "B. Banques, énergie, santé, télécoms, transport",
      "C. Commerce de détail seulement",
      "D. Agences de voyage",
    ],
    answers: ["B"],
  },
  {
    number: 17,
    type: "qcu",
    question: "La sécurité logique concerne principalement :",
    options: [
      "A. Les bâtiments et infrastructures physiques",
      "B. L'architecture immatérielle, les règles d'accès et l'organisation interne",
      "C. Les contrats et les aspects légaux",
      "D. Les budgets et finances",
    ],
    answers: ["B"],
  },
  {
    number: 18,
    type: "qcu",
    question: "La revue périodique des droits d'accès est essentielle pour :",
    options: [
      "A. Augmenter la vitesse des applications",
      "B. Garantir que les privilèges restent appropriés et détecter les anomalies",
      "C. Réduire la consommation électrique",
      "D. Améliorer l'ergonomie",
    ],
    answers: ["B"],
  },
  {
    number: 19,
    type: "qcu",
    question: "Quelle exigence de sécurité des télécommunications vise à absorber les attaques par saturation ?",
    options: [
      "A. Protocoles de chiffrement",
      "B. Protection anti-DDoS",
      "C. Filtrage des systèmes d'exploitation",
      "D. Segmentation des réseaux",
    ],
    answers: ["B"],
  },
  {
    number: 20,
    type: "qcu",
    question: "Les systèmes IDS/IPS visent à :",
    options: [
      "A. Compiler le code source",
      "B. Détecter et bloquer les tentatives d'intrusion",
      "C. Gérer les bases de données",
      "D. Créer des sauvegardes",
    ],
    answers: ["B"],
  },
  
  // Chapitre 2: Risques et menaces
  {
    number: 21,
    type: "qcu",
    question: "Quelle est la définition correcte du risque en sécurité informatique ?",
    options: [
      "A. Une faiblesse du système",
      "B. La possibilité qu'une menace exploite une vulnérabilité",
      "C. Un logiciel malveillant",
      "D. Une attaque en cours",
    ],
    answers: ["B"],
  },
  {
    number: 22,
    type: "qcu",
    question: "Qu'est-ce qu'une vulnérabilité ?",
    options: [
      "A. Une cause potentielle d'incident",
      "B. Une faiblesse du système exploitable",
      "C. Une action volontaire d'attaque",
      "D. Le succès d'une attaque",
    ],
    answers: ["B"],
  },
  {
    number: 23,
    type: "qcu",
    question: "Quelle est la différence entre une attaque et une intrusion ?",
    options: [
      "A. Il n'y a pas de différence",
      "B. L'attaque est l'action, l'intrusion est son succès",
      "C. L'intrusion précède toujours l'attaque",
      "D. L'attaque est passive, l'intrusion est active",
    ],
    answers: ["B"],
  },
  {
    number: 24,
    type: "qcu",
    question: "Les menaces se classent généralement en combien de catégories ?",
    options: [
      "A. Deux catégories",
      "B. Trois catégories : accidentelles, environnementales, délibérées",
      "C. Quatre catégories",
      "D. Cinq catégories",
    ],
    answers: ["B"],
  },
  {
    number: 25,
    type: "qcu",
    question: "Un exemple de menace environnementale est :",
    options: [
      "A. Un pirate informatique",
      "B. Une erreur de configuration",
      "C. Un incendie ou une inondation",
      "D. Un logiciel malveillant",
    ],
    answers: ["C"],
  },
  {
    number: 26,
    type: "qcu",
    question: "Quelle caractéristique distingue un virus d'un ver ?",
    options: [
      "A. Le virus est plus dangereux",
      "B. Le virus nécessite une action utilisateur pour se propager",
      "C. Le ver ne peut pas infecter de fichiers",
      "D. Le virus se propage automatiquement",
    ],
    answers: ["B"],
  },
  {
    number: 27,
    type: "qcu",
    question: "Un virus peut s'insérer dans :",
    options: [
      "A. Uniquement des fichiers exécutables",
      "B. Des documents avec macros ou des exécutables",
      "C. Uniquement des images",
      "D. Uniquement des vidéos",
    ],
    answers: ["B"],
  },
  {
    number: 28,
    type: "qcu",
    question: "Quelle est la particularité d'un ver informatique ?",
    options: [
      "A. Il nécessite toujours une intervention manuelle",
      "B. Il se propage automatiquement en exploitant des vulnérabilités",
      "C. Il ne peut infecter qu'un seul poste",
      "D. Il ne peut pas saturer le réseau",
    ],
    answers: ["B"],
  },
  {
    number: 29,
    type: "qcu",
    question: "Quel type de malware se présente comme légitime pour tromper l'utilisateur ?",
    options: [
      "A. Virus",
      "B. Ver",
      "C. Cheval de Troie",
      "D. Ransomware",
    ],
    answers: ["C"],
  },
  {
    number: 30,
    type: "qcu",
    question: "Un cheval de Troie se réplique-t-il nécessairement par lui-même ?",
    options: [
      "A. Oui, toujours",
      "B. Non, contrairement au ver",
      "C. Seulement sur les serveurs",
      "D. Uniquement le week-end",
    ],
    answers: ["B"],
  },
  {
    number: 31,
    type: "qcu",
    question: "Quel est l'impact principal d'un ransomware ?",
    options: [
      "A. Interception des communications",
      "B. Interruption via chiffrement des données et demande de rançon",
      "C. Modification des configurations système seulement",
      "D. Fabrication de faux documents",
    ],
    answers: ["B"],
  },
  {
    number: 32,
    type: "qcu",
    question: "Qu'est-ce que la double extorsion dans le contexte des ransomwares ?",
    options: [
      "A. Demander deux fois la même rançon",
      "B. Exfiltrer les données avant chiffrement puis menacer de les publier",
      "C. Infecter deux machines simultanément",
      "D. Utiliser deux algorithmes de chiffrement",
    ],
    answers: ["B"],
  },
  {
    number: 33,
    type: "qcu",
    question: "Les keyloggers sont un type de :",
    options: [
      "A. Antivirus",
      "B. Firewall",
      "C. Spyware",
      "D. Système de sauvegarde",
    ],
    answers: ["C"],
  },
  {
    number: 34,
    type: "qcu",
    question: "Les spywares peuvent être de type :",
    options: [
      "A. Uniquement logiciel",
      "B. Logiciel ou matériel (hardware)",
      "C. Uniquement matériel",
      "D. Uniquement réseau",
    ],
    answers: ["B"],
  },
  {
    number: 35,
    type: "qcu",
    question: "Un exemple de spyware matériel est :",
    options: [
      "A. Un virus",
      "B. Un overlay de clavier ou mini-caméra sur un DAB",
      "C. Un pare-feu",
      "D. Un routeur",
    ],
    answers: ["B"],
  },
  {
    number: 36,
    type: "qcu",
    question: "Que signifie DDoS ?",
    options: [
      "A. Direct Denial of System",
      "B. Distributed Denial of Service",
      "C. Digital Defense of Security",
      "D. Data Destruction of Servers",
    ],
    answers: ["B"],
  },
  {
    number: 37,
    type: "qcu",
    question: "L'objectif principal d'une attaque DDoS est de :",
    options: [
      "A. Voler des données",
      "B. Modifier des fichiers",
      "C. Rendre un service indisponible en épuisant ses ressources",
      "D. Installer un backdoor",
    ],
    answers: ["C"],
  },
  {
    number: 38,
    type: "qcu",
    question: "Une attaque DDoS peut servir de diversion pour :",
    options: [
      "A. Accélérer le réseau",
      "B. Masquer une exfiltration de données",
      "C. Améliorer les performances",
      "D. Réduire les coûts",
    ],
    answers: ["B"],
  },
  {
    number: 39,
    type: "qcu",
    question: "Le spamming est principalement utilisé comme vecteur pour :",
    options: [
      "A. La sauvegarde de données",
      "B. Le phishing et la distribution de malwares",
      "C. L'optimisation des performances",
      "D. La compression de fichiers",
    ],
    answers: ["B"],
  },
  {
    number: 40,
    type: "qcu",
    question: "Un impact typique d'un virus est :",
    options: [
      "A. Uniquement l'interception",
      "B. Principalement la modification ou corruption de fichiers",
      "C. Uniquement la fabrication",
      "D. Jamais l'interruption",
    ],
    answers: ["B"],
  },

  // Chapitre 3: Mécanismes de contrôle et de supervision
  {
    number: 41,
    type: "qcu",
    question: "Que signifie IDS ?",
    options: [
      "A. Internet Defense System",
      "B. Intrusion Detection System",
      "C. Internal Data Security",
      "D. Integrated Database Service",
    ],
    answers: ["B"],
  },
  {
    number: 42,
    type: "qcu",
    question: "Le principe de base d'un IDS est :",
    options: [
      "A. Bloquer toutes les connexions",
      "B. Repérer les anomalies du système pour mettre au jour les intrusions",
      "C. Accélérer le réseau",
      "D. Chiffrer les données",
    ],
    answers: ["B"],
  },
  {
    number: 43,
    type: "qcu",
    question: "Quelle est la différence principale entre NIDS et HIDS ?",
    options: [
      "A. NIDS surveille le réseau, HIDS surveille l'hôte",
      "B. NIDS est plus lent que HIDS",
      "C. HIDS surveille le réseau, NIDS surveille l'hôte",
      "D. Il n'y a pas de différence",
    ],
    answers: ["A"],
  },
  {
    number: 44,
    type: "qcu",
    question: "Un NIDS se concentre sur :",
    options: [
      "A. Les fichiers système locaux",
      "B. Le trafic réseau et les paquets de données",
      "C. Les journaux d'événements locaux uniquement",
      "D. Les processus CPU",
    ],
    answers: ["B"],
  },
  {
    number: 45,
    type: "qcu",
    question: "Un HIDS est implanté sur :",
    options: [
      "A. Le routeur principal",
      "B. Des machines individuelles pour surveiller les activités locales",
      "C. Le cloud uniquement",
      "D. Les câbles réseau",
    ],
    answers: ["B"],
  },
  {
    number: 46,
    type: "qcu",
    question: "Un IDS hybride combine :",
    options: [
      "A. HIDS et NIDS",
      "B. Uniquement des signatures",
      "C. Deux NIDS",
      "D. Uniquement des anomalies",
    ],
    answers: ["A"],
  },
  {
    number: 47,
    type: "qcu",
    question: "La détection basée sur les signatures compare le trafic à :",
    options: [
      "A. Un comportement normal préétabli",
      "B. Une base de données d'attaques connues",
      "C. Des règles de pare-feu",
      "D. Des logs système",
    ],
    answers: ["B"],
  },
  {
    number: 48,
    type: "qcu",
    question: "Quel est l'avantage principal de la détection basée sur les anomalies ?",
    options: [
      "A. Faible taux de faux positifs",
      "B. Rapide à mettre en place",
      "C. Détecte les attaques inconnues (0-day)",
      "D. Ne nécessite pas de mises à jour",
    ],
    answers: ["C"],
  },
  {
    number: 49,
    type: "qcu",
    question: "Quel est l'inconvénient majeur de la détection basée sur les signatures ?",
    options: [
      "A. Taux de faux positifs élevé",
      "B. Incapable de détecter de nouvelles attaques",
      "C. Trop lente",
      "D. Coûteuse en ressources uniquement",
    ],
    answers: ["B"],
  },
  {
    number: 50,
    type: "qcu",
    question: "La détection basée sur l'anomalie nécessite :",
    options: [
      "A. Aucune configuration",
      "B. Une phase d'apprentissage coûteuse en ressources",
      "C. Uniquement des signatures",
      "D. Pas de mises à jour",
    ],
    answers: ["B"],
  },
  {
    number: 51,
    type: "qcu",
    question: "Que signifie CIDS ?",
    options: [
      "A. Central Intrusion Detection System",
      "B. Collaborative Intrusion Detection System",
      "C. Cloud Intrusion Defense System",
      "D. Computer Integrated Data Security",
    ],
    answers: ["B"],
  },
  {
    number: 52,
    type: "qcu",
    question: "Un CIDS est créé pour pallier les lacunes des IDS contre :",
    options: [
      "A. Les attaques simples",
      "B. Les attaques distribuées ou parallèles",
      "C. Les virus uniquement",
      "D. Les erreurs de configuration",
    ],
    answers: ["B"],
  },
  {
    number: 53,
    type: "qcu",
    question: "Dans un CIDS centralisé, combien y a-t-il d'unités d'analyse ?",
    options: [
      "A. Plusieurs réparties",
      "B. Une seule centrale",
      "C. Une par capteur",
      "D. Aucune",
    ],
    answers: ["B"],
  },
  {
    number: 54,
    type: "qcu",
    question: "Quel est le principal inconvénient d'un CIDS centralisé ?",
    options: [
      "A. Coût élevé uniquement",
      "B. Point de défaillance unique et problèmes de scalabilité",
      "C. Complexité de configuration seulement",
      "D. Manque de précision",
    ],
    answers: ["B"],
  },
  {
    number: 55,
    type: "qcu",
    question: "Un CIDS décentralisé utilise une architecture :",
    options: [
      "A. Plate",
      "B. Hiérarchique",
      "C. Peer-to-peer",
      "D. Client-serveur simple",
    ],
    answers: ["B"],
  },
  {
    number: 56,
    type: "qcu",
    question: "Dans un CIDS décentralisé, que se passe-t-il à chaque niveau de la hiérarchie ?",
    options: [
      "A. Les données sont enrichies",
      "B. Des données sont perdues avant d'atteindre le sommet",
      "C. Les données sont chiffrées",
      "D. Les données sont sauvegardées",
    ],
    answers: ["B"],
  },
  {
    number: 57,
    type: "qcu",
    question: "Quelle architecture CIDS utilise le peer-to-peer (P2P) ?",
    options: [
      "A. CIDS centralisé",
      "B. CIDS décentralisé",
      "C. CIDS distribué",
      "D. CIDS hybride",
    ],
    answers: ["C"],
  },
  {
    number: 58,
    type: "qcu",
    question: "Les avantages d'un CIDS distribué incluent :",
    options: [
      "A. Point unique de défaillance",
      "B. Évolutivité et absence de point unique de défaillance",
      "C. Simplicité maximale",
      "D. Pas de surcharge réseau",
    ],
    answers: ["B"],
  },
  {
    number: 59,
    type: "qcu",
    question: "Un défi majeur du CIDS distribué est :",
    options: [
      "A. La vitesse",
      "B. L'établissement de la confiance entre les nœuds",
      "C. La taille des fichiers",
      "D. La couleur de l'interface",
    ],
    answers: ["B"],
  },
  {
    number: 60,
    type: "qcu",
    question: "Quelle est la différence fondamentale entre IDS et IPS ?",
    options: [
      "A. IDS détecte, IPS détecte et bloque",
      "B. IPS est plus lent",
      "C. IDS est actif, IPS est passif",
      "D. Il n'y a pas de différence",
    ],
    answers: ["A"],
  },
  {
    number: 61,
    type: "qcu",
    question: "Un IPS fonctionne en mode :",
    options: [
      "A. Passif uniquement",
      "B. Actif avec blocage automatique des attaques",
      "C. Observation sans intervention",
      "D. Analyse post-incident",
    ],
    answers: ["B"],
  },
  {
    number: 62,
    type: "qcu",
    question: "Un IDS envoie :",
    options: [
      "A. Des paquets réseau",
      "B. Des alertes à l'administrateur",
      "C. Des virus",
      "D. Des sauvegardes",
    ],
    answers: ["B"],
  },
  {
    number: 63,
    type: "qcu",
    question: "Un IPS prend des mesures automatiques comme :",
    options: [
      "A. Envoyer un email seulement",
      "B. Bloquer l'adresse IP source, désactiver des connexions",
      "C. Redémarrer le serveur",
      "D. Rien du tout",
    ],
    answers: ["B"],
  },
  {
    number: 64,
    type: "qcu",
    question: "Suricata et Snort sont des exemples de :",
    options: [
      "A. Antivirus",
      "B. IDS/IPS",
      "C. Pare-feu",
      "D. VPN",
    ],
    answers: ["B"],
  },
  {
    number: 65,
    type: "qcu",
    question: "Quelle est une caractéristique de Suricata par rapport à Snort ?",
    options: [
      "A. Architecture monothread",
      "B. Architecture multithread hautes performances",
      "C. Moins de fonctionnalités",
      "D. Plus ancien",
    ],
    answers: ["B"],
  },
  {
    number: 66,
    type: "qcu",
    question: "Snort a été créé par :",
    options: [
      "A. Google",
      "B. Martin Roesch et maintenu par Cisco Systems",
      "C. Microsoft",
      "D. Amazon",
    ],
    answers: ["B"],
  },
  {
    number: 67,
    type: "qcu",
    question: "Dans un système IDS augmenté par ML, quel est le rôle de l'apprentissage automatique ?",
    options: [
      "A. Remplacer complètement les signatures",
      "B. Détecter les comportements anormaux et attaques 0-day",
      "C. Accélérer le réseau",
      "D. Chiffrer les communications",
    ],
    answers: ["B"],
  },
  {
    number: 68,
    type: "qcu",
    question: "Dans l'architecture d'IDS basée sur les anomalies, quelle est la première étape ?",
    options: [
      "A. Déploiement en production",
      "B. Récupération des données réseaux réels",
      "C. Optimisation des hyperparamètres",
      "D. Génération de rapports",
    ],
    answers: ["B"],
  },
  {
    number: 69,
    type: "qcu",
    question: "Quel outil peut être utilisé pour capturer des paquets réseau ?",
    options: [
      "A. Microsoft Word",
      "B. Wireshark",
      "C. Photoshop",
      "D. Excel",
    ],
    answers: ["B"],
  },
  {
    number: 70,
    type: "qcu",
    question: "À quelle couche OSI s'intéresse principalement l'IDS pour la détection ?",
    options: [
      "A. Couche physique uniquement",
      "B. Couche transport (TCP, UDP, ports, flags)",
      "C. Couche présentation uniquement",
      "D. Couche application seulement",
    ],
    answers: ["B"],
  },
  {
    number: 71,
    type: "qcu",
    question: "Dans le dataset NSL-KDD, combien d'attributs décrivent chaque connexion réseau ?",
    options: [
      "A. 20",
      "B. 35",
      "C. 41 caractéristiques + 2 étiquettes",
      "D. 50",
    ],
    answers: ["C"],
  },
  {
    number: 72,
    type: "qcu",
    question: "NSL-KDD est une version améliorée de quel dataset ?",
    options: [
      "A. MNIST",
      "B. KDD Cup 1999",
      "C. ImageNet",
      "D. COCO",
    ],
    answers: ["B"],
  },
  {
    number: 73,
    type: "qcu",
    question: "Les types d'attaques dans NSL-KDD incluent :",
    options: [
      "A. Uniquement DoS",
      "B. DoS, Probe, R2L, U2R",
      "C. Uniquement Probe",
      "D. Aucune catégorie",
    ],
    answers: ["B"],
  },
  {
    number: 74,
    type: "qcu",
    question: "Que signifie TP (True Positive) dans une matrice de confusion ?",
    options: [
      "A. Fausse alerte",
      "B. Attaque correctement détectée",
      "C. Trafic normal détecté comme normal",
      "D. Attaque manquée",
    ],
    answers: ["B"],
  },
  {
    number: 75,
    type: "qcu",
    question: "Que signifie FP (False Positive) ?",
    options: [
      "A. Attaque détectée correctement",
      "B. Trafic normal classé comme attaque (fausse alerte)",
      "C. Attaque manquée",
      "D. Trafic normal détecté comme normal",
    ],
    answers: ["B"],
  },
  {
    number: 76,
    type: "qcu",
    question: "Que signifie TN (True Negative) ?",
    options: [
      "A. Attaque détectée",
      "B. Trafic normal correctement identifié comme normal",
      "C. Fausse alerte",
      "D. Attaque manquée",
    ],
    answers: ["B"],
  },
  {
    number: 77,
    type: "qcu",
    question: "Que signifie FN (False Negative) ?",
    options: [
      "A. Attaque détectée",
      "B. Trafic normal comme attaque",
      "C. Attaque manquée (non détectée)",
      "D. Trafic normal correctement identifié",
    ],
    answers: ["C"],
  },
  {
    number: 78,
    type: "qcu",
    question: "La formule du Recall (Rappel) est :",
    options: [
      "A. TP / (TP + FP)",
      "B. TP / (TP + FN)",
      "C. TN / (TN + FP)",
      "D. (TP + TN) / Total",
    ],
    answers: ["B"],
  },
  {
    number: 79,
    type: "qcu",
    question: "La Precision mesure :",
    options: [
      "A. La capacité à détecter toutes les attaques",
      "B. La proportion de vraies attaques parmi les détections",
      "C. Le taux d'erreur global",
      "D. La vitesse de détection",
    ],
    answers: ["B"],
  },
  {
    number: 80,
    type: "qcu",
    question: "Le F1-score combine :",
    options: [
      "A. Précision et Rappel",
      "B. Vitesse et Efficacité",
      "C. Coût et Performance",
      "D. Accuracy et FPR",
    ],
    answers: ["A"],
  },
  {
    number: 81,
    type: "qcu",
    question: "Un taux de FPR élevé signifie :",
    options: [
      "A. Beaucoup de vraies attaques détectées",
      "B. Beaucoup de fausses alertes",
      "C. Peu d'attaques manquées",
      "D. Excellente précision",
    ],
    answers: ["B"],
  },
  {
    number: 82,
    type: "qcu",
    question: "Un taux de FNR élevé signifie :",
    options: [
      "A. Beaucoup d'attaques correctement détectées",
      "B. Beaucoup d'attaques manquées",
      "C. Peu de fausses alertes",
      "D. Excellente disponibilité",
    ],
    answers: ["B"],
  },
  {
    number: 83,
    type: "qcu",
    question: "Quels modèles ML sont souvent utilisés pour la détection d'anomalies ?",
    options: [
      "A. Word2Vec uniquement",
      "B. Isolation Forest, One-Class SVM, LSTM",
      "C. K-means uniquement",
      "D. Aucun modèle",
    ],
    answers: ["B"],
  },
  {
    number: 84,
    type: "qcu",
    question: "Pour la classification d'attaques, quels modèles supervisés sont utilisés ?",
    options: [
      "A. Random Forest, Gradient Boosting, XGBoost",
      "B. Uniquement la régression linéaire",
      "C. Aucun modèle supervisé",
      "D. Uniquement des réseaux non supervisés",
    ],
    answers: ["A"],
  },
  {
    number: 85,
    type: "qcu",
    question: "L'optimisation dans le pipeline IDS consiste à :",
    options: [
      "A. Ne jamais modifier le modèle",
      "B. Analyser les erreurs et ajuster pipeline, features et hyperparamètres",
      "C. Augmenter la taille des logs",
      "D. Réduire le nombre de features systématiquement",
    ],
    answers: ["B"],
  },

  // Chapitre 4: Sécurité applicative et DevSecOps
  {
    number: 86,
    type: "qcu",
    question: "Que signifie DevSecOps ?",
    options: [
      "A. Development Security Operations",
      "B. Device Security Optimization",
      "C. Developer Security Options",
      "D. Digital Security for Operations",
    ],
    answers: ["A"],
  },
  {
    number: 87,
    type: "qcu",
    question: "L'objectif principal du DevSecOps est de :",
    options: [
      "A. Ralentir le développement pour plus de sécurité",
      "B. Intégrer la sécurité dès le début et tout au long du cycle",
      "C. Remplacer les développeurs par des outils",
      "D. Éliminer les tests manuels",
    ],
    answers: ["B"],
  },
  {
    number: 88,
    type: "qcu",
    question: "DevSecOps combine :",
    options: [
      "A. Uniquement le développement",
      "B. Développement (Dev), Sécurité (Sec) et Opérations (Ops)",
      "C. Uniquement la sécurité",
      "D. Design et Marketing",
    ],
    answers: ["B"],
  },
  {
    number: 89,
    type: "qcu",
    question: "Que signifie CI dans le contexte DevSecOps ?",
    options: [
      "A. Computer Integration",
      "B. Continuous Integration",
      "C. Central Infrastructure",
      "D. Code Implementation",
    ],
    answers: ["B"],
  },
  {
    number: 90,
    type: "qcu",
    question: "L'intégration continue (CI) consiste à :",
    options: [
      "A. Déployer automatiquement en production",
      "B. Tester automatiquement chaque modification du code",
      "C. Sauvegarder le code régulièrement",
      "D. Documenter le code",
    ],
    answers: ["B"],
  },
  {
    number: 91,
    type: "qcu",
    question: "Dans la CI, si un problème est détecté, que se passe-t-il ?",
    options: [
      "A. Le déploiement continue",
      "B. Le déploiement est bloqué et les développeurs sont notifiés",
      "C. Rien ne se passe",
      "D. Le code est supprimé",
    ],
    answers: ["B"],
  },
  {
    number: 92,
    type: "qcu",
    question: "Le déploiement continu (CD) implique :",
    options: [
      "A. Des déploiements manuels fréquents",
      "B. L'automatisation complète de la mise en production",
      "C. La sauvegarde des données",
      "D. La surveillance des logs uniquement",
    ],
    answers: ["B"],
  },
  {
    number: 93,
    type: "qcu",
    question: "Dans le CD, les mises à jour sont déployées :",
    options: [
      "A. Une fois par an",
      "B. Automatiquement dès qu'elles passent les tests",
      "C. Manuellement toujours",
      "D. Jamais",
    ],
    answers: ["B"],
  },
  {
    number: 94,
    type: "qcu",
    question: "La sécurité continue (CS) vise à :",
    options: [
      "A. Tester la sécurité une fois par an",
      "B. Intégrer des contrôles de sécurité automatisés en permanence",
      "C. Former les utilisateurs régulièrement seulement",
      "D. Mettre à jour les antivirus une fois",
    ],
    answers: ["B"],
  },
  {
    number: 95,
    type: "qcu",
    question: "La modélisation des menaces (Threat Modeling) doit être réalisée :",
    options: [
      "A. Après le déploiement",
      "B. Pendant les tests uniquement",
      "C. Dès la phase de planification",
      "D. Uniquement en cas d'incident",
    ],
    answers: ["C"],
  },
  {
    number: 96,
    type: "qcu",
    question: "Quel outil OWASP est utilisé pour la modélisation des menaces ?",
    options: [
      "A. OWASP ZAP",
      "B. OWASP Threat Dragon",
      "C. OWASP Dependency-Check",
      "D. OWASP Top 10",
    ],
    answers: ["B"],
  },
  {
    number: 97,
    type: "qcu",
    question: "Le modèle STRIDE catégorise les menaces selon :",
    options: [
      "A. Leur source géographique",
      "B. Six types : Spoofing, Tampering, Repudiation, Information Disclosure, DoS, Elevation of Privilege",
      "C. Leur niveau de dangerosité uniquement",
      "D. Leur fréquence d'occurrence",
    ],
    answers: ["B"],
  },
  {
    number: 98,
    type: "qcu",
    question: "Dans STRIDE, que signifie 'Spoofing' ?",
    options: [
      "A. Augmentation de privilèges",
      "B. Usurpation d'identité",
      "C. Modification de données",
      "D. Divulgation d'informations",
    ],
    answers: ["B"],
  },
  {
    number: 99,
    type: "qcu",
    question: "Dans STRIDE, que signifie 'Tampering' ?",
    options: [
      "A. Déni de service",
      "B. Modification non autorisée de données",
      "C. Non-répudiation",
      "D. Usurpation",
    ],
    answers: ["B"],
  },
  {
    number: 100,
    type: "qcu",
    question: "Dans STRIDE, que signifie 'Repudiation' ?",
    options: [
      "A. Divulgation d'informations",
      "B. Capacité à nier avoir effectué une action",
      "C. Élévation de privilèges",
      "D. Saturation de ressources",
    ],
    answers: ["B"],
  },
  {
    number: 101,
    type: "qcu",
    question: "Le modèle LINDDUN se concentre sur :",
    options: [
      "A. Les performances système",
      "B. La protection de la vie privée et la conformité",
      "C. La vitesse de développement",
      "D. Les coûts",
    ],
    answers: ["B"],
  },
  {
    number: 102,
    type: "qcu",
    question: "Le modèle CIA évalue l'impact sur :",
    options: [
      "A. Confidentialité, Intégrité, Disponibilité",
      "B. Coût, Innovation, Agilité",
      "C. Communication, Information, Action",
      "D. Code, Infrastructure, Architecture",
    ],
    answers: ["A"],
  },
  {
    number: 103,
    type: "qcu",
    question: "Un Data Flow Diagram (DFD) dans Threat Dragon sert à :",
    options: [
      "A. Mesurer les performances",
      "B. Représenter les flux de données entre composants",
      "C. Calculer les coûts",
      "D. Planifier les sprints",
    ],
    answers: ["B"],
  },
  {
    number: 104,
    type: "qcu",
    question: "Dans un DFD, les flèches représentent :",
    options: [
      "A. Les serveurs",
      "B. Les flux de données (requêtes, réponses)",
      "C. Les utilisateurs",
      "D. Les coûts",
    ],
    answers: ["B"],
  },
  {
    number: 105,
    type: "qcu",
    question: "Le document Security Requirements Specification (SRS) contient :",
    options: [
      "A. Uniquement le code source",
      "B. Les objectifs de sécurité, exigences minimales, critères d'acceptation",
      "C. Les budgets uniquement",
      "D. Les CV des développeurs",
    ],
    answers: ["B"],
  },
  {
    number: 106,
    type: "qcu",
    question: "Les exigences de sécurité doivent être :",
    options: [
      "A. Définies une seule fois",
      "B. Révisées régulièrement à mesure que le système évolue",
      "C. Ignorées après la planification",
      "D. Gardées secrètes",
    ],
    answers: ["B"],
  },
  {
    number: 107,
    type: "qcu",
    question: "Que signifie SAST ?",
    options: [
      "A. Software Application Security Testing",
      "B. Static Application Security Testing",
      "C. System Automated Security Test",
      "D. Security Analysis for Software Tools",
    ],
    answers: ["B"],
  },
  {
    number: 108,
    type: "qcu",
    question: "Le SAST analyse :",
    options: [
      "A. L'application en cours d'exécution",
      "B. Le code source sans l'exécuter",
      "C. Le trafic réseau",
      "D. Les logs système",
    ],
    answers: ["B"],
  },
  {
    number: 109,
    type: "qcu",
    question: "Bandit est un outil SAST pour quel langage ?",
    options: [
      "A. Java",
      "B. JavaScript",
      "C. Python",
      "D. C++",
    ],
    answers: ["C"],
  },
  {
    number: 110,
    type: "qcu",
    question: "Dans un rapport SAST Bandit, que signifie CWE ?",
    options: [
      "A. Code Warning Error",
      "B. Common Weakness Enumeration",
      "C. Critical Web Exploit",
      "D. Cyber Warfare Element",
    ],
    answers: ["B"],
  },
  {
    number: 111,
    type: "qcu",
    question: "Dans un rapport Bandit, 'Severity' indique :",
    options: [
      "A. La vitesse de l'attaque",
      "B. L'importance potentielle de la vulnérabilité (LOW/MEDIUM/HIGH)",
      "C. Le coût de correction",
      "D. Le nombre de lignes affectées",
    ],
    answers: ["B"],
  },
  {
    number: 112,
    type: "qcu",
    question: "Dans un rapport Bandit, 'Confidence' représente :",
    options: [
      "A. La vitesse d'exécution",
      "B. La certitude que c'est vraiment une vulnérabilité",
      "C. Le nombre de développeurs",
      "D. La taille du fichier",
    ],
    answers: ["B"],
  },
  {
    number: 113,
    type: "qcu",
    question: "MITRE Corporation gère quel catalogue mondial ?",
    options: [
      "A. Uniquement CVE",
      "B. CVE et CWE",
      "C. Uniquement OWASP Top 10",
      "D. ISO 27001",
    ],
    answers: ["B"],
  },
  {
    number: 114,
    type: "qcu",
    question: "Les pratiques de Secure Coding incluent :",
    options: [
      "A. Ignorer la validation des entrées",
      "B. Validation stricte des entrées, gestion correcte des exceptions, protection des secrets",
      "C. Mettre les mots de passe dans le code",
      "D. Ne jamais tester le code",
    ],
    answers: ["B"],
  },
  {
    number: 115,
    type: "qcu",
    question: "Le principe du moindre privilège en Secure Coding signifie :",
    options: [
      "A. Donner tous les droits à tout le monde",
      "B. N'accorder que les permissions strictement nécessaires",
      "C. Ne jamais utiliser de contrôle d'accès",
      "D. Utiliser un seul compte administrateur",
    ],
    answers: ["B"],
  },
  {
    number: 116,
    type: "qcu",
    question: "Que signifie SCA ?",
    options: [
      "A. Security Control Analysis",
      "B. Software Composition Analysis",
      "C. System Configuration Audit",
      "D. Source Code Assessment",
    ],
    answers: ["B"],
  },
  {
    number: 117,
    type: "qcu",
    question: "Un outil SCA analyse principalement :",
    options: [
      "A. Le code source de l'application",
      "B. Les dépendances et composants tiers",
      "C. Le trafic réseau",
      "D. Les configurations système",
    ],
    answers: ["B"],
  },
  {
    number: 118,
    type: "qcu",
    question: "Trivy est un outil de :",
    options: [
      "A. SAST",
      "B. SCA (Software Composition Analysis)",
      "C. DAST",
      "D. Pentesting manuel",
    ],
    answers: ["B"],
  },
  {
    number: 119,
    type: "qcu",
    question: "Trivy peut scanner :",
    options: [
      "A. Uniquement des fichiers texte",
      "B. requirements.txt, dépendances Python, images Docker",
      "C. Uniquement des vidéos",
      "D. Uniquement des bases de données",
    ],
    answers: ["B"],
  },
  {
    number: 120,
    type: "qcu",
    question: "Que signifie SBOM ?",
    options: [
      "A. Security Backup and Operation Manual",
      "B. Software Bill of Materials",
      "C. System Baseline for Operations Management",
      "D. Security Breach Observation Method",
    ],
    answers: ["B"],
  },
  {
    number: 121,
    type: "qcu",
    question: "Un SBOM contient :",
    options: [
      "A. Uniquement le code source",
      "B. L'inventaire complet des composants, dépendances, versions et licences",
      "C. Les logs d'exécution",
      "D. Les configurations réseau",
    ],
    answers: ["B"],
  },
  {
    number: 122,
    type: "qcu",
    question: "Quand doit être généré un SBOM ?",
    options: [
      "A. Une fois par an",
      "B. Automatiquement à chaque build",
      "C. Jamais",
      "D. Uniquement en cas d'incident",
    ],
    answers: ["B"],
  },
  {
    number: 123,
    type: "qcu",
    question: "L'objectif de la signature des artefacts est de garantir :",
    options: [
      "A. La rapidité de déploiement",
      "B. L'authenticité et l'intégrité",
      "C. La compatibilité multiplateforme",
      "D. La compression des fichiers",
    ],
    answers: ["B"],
  },
  {
    number: 124,
    type: "qcu",
    question: "Cosign et Sigstore sont des outils pour :",
    options: [
      "A. La compilation de code",
      "B. La signature cryptographique des artefacts",
      "C. La gestion de bases de données",
      "D. L'édition de texte",
    ],
    answers: ["B"],
  },
  {
    number: 125,
    type: "qcu",
    question: "Que signifie CVE ?",
    options: [
      "A. Computer Virus Encyclopedia",
      "B. Common Vulnerabilities and Exposures",
      "C. Cyber Vector Enumeration",
      "D. Critical Vulnerability Evaluation",
    ],
    answers: ["B"],
  },
  {
    number: 126,
    type: "qcu",
    question: "Un CVE est :",
    options: [
      "A. Un logiciel antivirus",
      "B. Un identifiant unique standardisé pour une vulnérabilité connue",
      "C. Un type de virus",
      "D. Un protocole réseau",
    ],
    answers: ["B"],
  },
  {
    number: 127,
    type: "qcu",
    question: "Les builds reproductibles visent à :",
    options: [
      "A. Accélérer la compilation",
      "B. Produire exactement le même artefact à partir du même code",
      "C. Réduire la taille des binaires",
      "D. Améliorer les performances seulement",
    ],
    answers: ["B"],
  },
  {
    number: 128,
    type: "qcu",
    question: "Les attestations de provenance prouvent :",
    options: [
      "A. La vitesse de compilation",
      "B. L'origine et le processus de création d'un artefact",
      "C. La compatibilité avec différents OS",
      "D. Le nombre de lignes de code",
    ],
    answers: ["B"],
  },
  {
    number: 129,
    type: "qcu",
    question: "La Supply Chain Security vise à garantir :",
    options: [
      "A. La rapidité de livraison",
      "B. Que les composants et artefacts n'ont pas été modifiés ou compromis",
      "C. Le coût minimal",
      "D. La taille minimale des fichiers",
    ],
    answers: ["B"],
  },
  {
    number: 130,
    type: "qcu",
    question: "Les quatre piliers de la Supply Chain Security sont :",
    options: [
      "A. Vitesse, coût, qualité, sécurité",
      "B. Transparence, vérifiabilité, intégrité, provenance",
      "C. Code, test, build, deploy",
      "D. Dev, sec, ops, qa",
    ],
    answers: ["B"],
  },
  {
    number: 131,
    type: "qcu",
    question: "Que signifie DAST ?",
    options: [
      "A. Dynamic Application Security Testing",
      "B. Data Analysis and Security Tools",
      "C. Digital Asset Security Tracking",
      "D. Database Application System Test",
    ],
    answers: ["A"],
  },
  {
    number: 132,
    type: "qcu",
    question: "Le DAST analyse l'application :",
    options: [
      "A. Au niveau du code source",
      "B. En cours d'exécution (approche boîte noire)",
      "C. Pendant la compilation",
      "D. Avant le développement",
    ],
    answers: ["B"],
  },
  {
    number: 133,
    type: "qcu",
    question: "OWASP ZAP est un outil de :",
    options: [
      "A. SAST",
      "B. SCA",
      "C. DAST",
      "D. Compilation",
    ],
    answers: ["C"],
  },
  {
    number: 134,
    type: "qcu",
    question: "OWASP ZAP interagit avec l'application :",
    options: [
      "A. En lisant le code source",
      "B. Comme le ferait un attaquant, en envoyant des requêtes malveillantes",
      "C. En modifiant la base de données",
      "D. En arrêtant les serveurs",
    ],
    answers: ["B"],
  },
  {
    number: 135,
    type: "qcu",
    question: "Le DAST peut détecter des failles comme :",
    options: [
      "A. Uniquement des erreurs de compilation",
      "B. Injections SQL, XSS, erreurs de configuration",
      "C. Uniquement des bugs visuels",
      "D. Rien du tout",
    ],
    answers: ["B"],
  },
  {
    number: 136,
    type: "qcu",
    question: "Le fuzzing consiste à :",
    options: [
      "A. Optimiser le code",
      "B. Injecter des données aléatoires ou malformées pour provoquer des erreurs",
      "C. Compresser les fichiers",
      "D. Accélérer les tests",
    ],
    answers: ["B"],
  },
  {
    number: 137,
    type: "qcu",
    question: "Le fuzzing est particulièrement utile pour :",
    options: [
      "A. Les interfaces graphiques seulement",
      "B. Les API, parseurs de fichiers et services réseau",
      "C. Les bases de données seulement",
      "D. Les feuilles de style CSS",
    ],
    answers: ["B"],
  },
  {
    number: 138,
    type: "qcu",
    question: "Que signifie IAST ?",
    options: [
      "A. Integrated Application Security Testing",
      "B. Interactive Application Security Testing",
      "C. Internal Automated Security Tool",
      "D. Infrastructure Analysis and Security Test",
    ],
    answers: ["B"],
  },
  {
    number: 139,
    type: "qcu",
    question: "IAST combine :",
    options: [
      "A. SAST et SCA",
      "B. Analyse dynamique et instrumentation du code",
      "C. DAST et pentest manuel",
      "D. Firewall et IDS",
    ],
    answers: ["B"],
  },
  {
    number: 140,
    type: "qcu",
    question: "IAST fonctionne en :",
    options: [
      "A. Lisant uniquement le code source",
      "B. Exécutant l'application dans un environnement instrumenté",
      "C. Ne testant jamais l'application",
      "D. Compilant le code seulement",
    ],
    answers: ["B"],
  },
  {
    number: 141,
    type: "qcu",
    question: "Que signifie RASP ?",
    options: [
      "A. Rapid Application Security Protocol",
      "B. Runtime Application Self-Protection",
      "C. Remote Access Security Policy",
      "D. Real-time Analysis and Security Platform",
    ],
    answers: ["B"],
  },
  {
    number: 142,
    type: "qcu",
    question: "RASP fonctionne :",
    options: [
      "A. Au niveau du code source uniquement",
      "B. Au cœur de l'application en temps réel pendant l'exécution",
      "C. Uniquement pendant les tests",
      "D. Avant la compilation seulement",
    ],
    answers: ["B"],
  },
  {
    number: 143,
    type: "qcu",
    question: "La différence principale entre WAF et RASP est :",
    options: [
      "A. Il n'y a pas de différence",
      "B. RASP travaille au cœur de l'application avec meilleure compréhension du contexte",
      "C. WAF est plus rapide toujours",
      "D. RASP ne détecte rien",
    ],
    answers: ["B"],
  },
  {
    number: 144,
    type: "qcu",
    question: "Que signifie SIEM ?",
    options: [
      "A. System Information and Event Manager",
      "B. Security Information and Event Management",
      "C. Software Integration for Enterprise Management",
      "D. Secure Internet and Email Monitoring",
    ],
    answers: ["B"],
  },
  {
    number: 145,
    type: "qcu",
    question: "Le SIEM permet de :",
    options: [
      "A. Développer des applications",
      "B. Centraliser et corréler les événements de sécurité",
      "C. Compiler du code",
      "D. Gérer les versions",
    ],
    answers: ["B"],
  },
  {
    number: 146,
    type: "qcu",
    question: "La corrélation dans un SIEM sert à :",
    options: [
      "A. Compresser les logs",
      "B. Identifier des attaques complexes en reliant des événements apparemment indépendants",
      "C. Accélérer le réseau",
      "D. Sauvegarder les données",
    ],
    answers: ["B"],
  },
  {
    number: 147,
    type: "qcu",
    question: "Un SIEM peut détecter des incidents comme :",
    options: [
      "A. Uniquement les erreurs de syntaxe",
      "B. Brute force, SQLi, XSS, accès anormal",
      "C. Uniquement les bugs visuels",
      "D. Les fautes d'orthographe",
    ],
    answers: ["B"],
  },
  {
    number: 148,
    type: "qcu",
    question: "Que signifie SOAR dans le contexte SIEM ?",
    options: [
      "A. Simple Operations and Reporting",
      "B. Security Orchestration, Automation and Response",
      "C. System Observation and Risk",
      "D. Software Operations and Recovery",
    ],
    answers: ["B"],
  },
  {
    number: 149,
    type: "qcu",
    question: "Jenkins est principalement utilisé pour :",
    options: [
      "A. La gestion de bases de données",
      "B. L'intégration et le déploiement continus (CI/CD)",
      "C. Le développement d'interfaces graphiques",
      "D. La virtualisation",
    ],
    answers: ["B"],
  },
  {
    number: 150,
    type: "qcu",
    question: "Docker est une technologie de :",
    options: [
      "A. Base de données",
      "B. Conteneurisation",
      "C. Réseau uniquement",
      "D. Système d'exploitation complet",
    ],
    answers: ["B"],
  },
  {
    number: 151,
    type: "qcu",
    question: "Un pipeline CI/CD typique inclut les étapes suivantes dans quel ordre ?",
    options: [
      "A. Deploy → Build → Test → Code",
      "B. Code → Build → Test → Deploy",
      "C. Test → Code → Build → Deploy",
      "D. Build → Code → Deploy → Test",
    ],
    answers: ["B"],
  },
  {
    number: 152,
    type: "qcu",
    question: "Dans Jenkins, un 'stage' représente :",
    options: [
      "A. Une phase du pipeline (ex: Build, Test, Deploy)",
      "B. Un serveur physique",
      "C. Un utilisateur",
      "D. Une base de données",
    ],
    answers: ["A"],
  },
  {
    number: 153,
    type: "qcu",
    question: "Vulpy est :",
    options: [
      "A. Un outil de sécurité",
      "B. Une application web Python intentionnellement vulnérable pour les tests",
      "C. Un framework de développement",
      "D. Un système d'exploitation",
    ],
    answers: ["B"],
  },
  {
    number: 154,
    type: "qcu",
    question: "Dans le contexte DevSecOps, Security by Design signifie :",
    options: [
      "A. Tester la sécurité après le développement",
      "B. Intégrer la sécurité dès la conception",
      "C. Utiliser uniquement des outils open-source",
      "D. Externaliser la sécurité",
    ],
    answers: ["B"],
  },
  {
    number: 155,
    type: "qcu",
    question: "Quel fichier contient les dépendances d'un projet Python ?",
    options: [
      "A. package.json",
      "B. requirements.txt",
      "C. dependencies.yaml",
      "D. pom.xml",
    ],
    answers: ["B"],
  },
  {
    number: 156,
    type: "qcu",
    question: "Dans un rapport SCA, la colonne 'Vulnerability ID' contient généralement :",
    options: [
      "A. Le nom du développeur",
      "B. Un identifiant CVE",
      "C. Le numéro de ligne",
      "D. L'adresse IP",
    ],
    answers: ["B"],
  },
  {
    number: 157,
    type: "qcu",
    question: "Dans un rapport SCA, la version 'Fixed' indique :",
    options: [
      "A. La version actuellement installée",
      "B. La version qui corrige la vulnérabilité",
      "C. La version la plus ancienne",
      "D. La version la plus lourde",
    ],
    answers: ["B"],
  },
  {
    number: 158,
    type: "qcu",
    question: "La phase de planification DevSecOps doit produire :",
    options: [
      "A. Uniquement du code",
      "B. Threat Model, Security Requirements Specification et documentation",
      "C. Uniquement des tests unitaires",
      "D. La documentation utilisateur finale seulement",
    ],
    answers: ["B"],
  },
  {
    number: 159,
    type: "qcu",
    question: "La documentation de sécurité doit être :",
    options: [
      "A. Écrite une fois et jamais modifiée",
      "B. Vivante, versionnée et mise à jour avec le système",
      "C. Gardée secrète toujours",
      "D. Supprimée après la livraison",
    ],
    answers: ["B"],
  },
  {
    number: 160,
    type: "qcu",
    question: "Le principe de défense en profondeur (defense in depth) signifie :",
    options: [
      "A. Une seule couche de sécurité très forte",
      "B. Plusieurs couches de sécurité complémentaires",
      "C. Pas de sécurité physique",
      "D. Uniquement des contrôles logiciels",
    ],
    answers: ["B"],
  },
  {
    number: 161,
    type: "qcu",
    question: "La revue de code est importante car elle permet :",
    options: [
      "A. D'accélérer la compilation",
      "B. De détecter des erreurs logiques et de logique métier que les outils automatiques ratent",
      "C. De réduire la taille du code",
      "D. D'automatiser les tests uniquement",
    ],
    answers: ["B"],
  },
  {
    number: 162,
    type: "qcu",
    question: "Les protocoles obsolètes à désactiver incluent :",
    options: [
      "A. TLS 1.3 et SSH",
      "B. SSLv3 et Telnet",
      "C. HTTPS et SFTP",
      "D. IPsec et VPN",
    ],
    answers: ["B"],
  },
  {
    number: 163,
    type: "qcu",
    question: "La segmentation réseau vise à :",
    options: [
      "A. Augmenter la vitesse uniquement",
      "B. Limiter la propagation d'incidents et compartimenter",
      "C. Réduire les coûts seulement",
      "D. Simplifier l'administration uniquement",
    ],
    answers: ["B"],
  },
  {
    number: 164,
    type: "qcu",
    question: "Un système anti-DDoS a pour objectif principal de :",
    options: [
      "A. Accélérer le réseau",
      "B. Garantir la disponibilité en absorbant les attaques par saturation",
      "C. Chiffrer les données",
      "D. Authentifier les utilisateurs",
    ],
    answers: ["B"],
  },
  {
    number: 165,
    type: "qcu",
    question: "La gestion des secrets dans le code consiste à :",
    options: [
      "A. Mettre les mots de passe en commentaires",
      "B. Ne jamais stocker de clés/tokens/mots de passe en clair dans le code",
      "C. Utiliser des mots de passe simples",
      "D. Partager les secrets par email",
    ],
    answers: ["B"],
  },
  {
    number: 166,
    type: "qcu",
    question: "Les dépendances transitives sont :",
    options: [
      "A. Les dépendances directes du projet",
      "B. Les dépendances des dépendances",
      "C. Les fichiers temporaires",
      "D. Les variables globales",
    ],
    answers: ["B"],
  },
  {
    number: 167,
    type: "qcu",
    question: "L'objectif de la journalisation (logging) est de :",
    options: [
      "A. Ralentir l'application",
      "B. Tracer les événements pour analyse, investigation et audit",
      "C. Augmenter la taille des fichiers",
      "D. Compliquer le débogage",
    ],
    answers: ["B"],
  },
  {
    number: 168,
    type: "qcu",
    question: "La mise en production en DevSecOps doit toujours inclure :",
    options: [
      "A. Uniquement le déploiement du code",
      "B. Surveillance, détection (IDS/IPS), SIEM et gestion des incidents",
      "C. Seulement des sauvegardes",
      "D. Uniquement l'interface utilisateur",
    ],
    answers: ["B"],
  },
  {
    number: 169,
    type: "qcu",
    question: "OWASP SAMM est :",
    options: [
      "A. Un outil de scan",
      "B. Un modèle de maturité pour la sécurité logicielle",
      "C. Un langage de programmation",
      "D. Un système d'exploitation",
    ],
    answers: ["B"],
  },
  {
    number: 170,
    type: "qcu",
    question: "Dans OWASP SAMM, la pratique Security Requirements (SR) consiste à :",
    options: [
      "A. Ignorer la sécurité",
      "B. Formaliser les exigences de sécurité à partir des objectifs métiers",
      "C. Uniquement coder rapidement",
      "D. Ne jamais documenter",
    ],
    answers: ["B"],
  },
  {
    number: 171,
    type: "qcu",
    question: "Les exigences de sécurité doivent être testées :",
    options: [
      "A. Jamais",
      "B. Automatiquement à chaque étape du pipeline CI/CD",
      "C. Une fois par an seulement",
      "D. Uniquement manuellement",
    ],
    answers: ["B"],
  },
  {
    number: 172,
    type: "qcu",
    question: "Le dilemme entre sécurité et délai de livraison se résout par :",
    options: [
      "A. Ignorer la sécurité",
      "B. Une logique de priorisation et gestion du risque avec seuils de tolérance",
      "C. Retarder indéfiniment la livraison",
      "D. Ne jamais livrer",
    ],
    answers: ["B"],
  },
  {
    number: 173,
    type: "qcu",
    question: "Les vulnérabilités critiques dans le pipeline doivent :",
    options: [
      "A. Être ignorées",
      "B. Bloquer le cycle jusqu'à correction",
      "C. Être documentées mais jamais corrigées",
      "D. Être transmises au client",
    ],
    answers: ["B"],
  },
  {
    number: 174,
    type: "qcu",
    question: "Les anomalies mineures détectées peuvent être :",
    options: [
      "A. Ignorées complètement",
      "B. Suivies, documentées et corrigées ultérieurement",
      "C. Transformées en fonctionnalités",
      "D. Supprimées du rapport",
    ],
    answers: ["B"],
  },
  {
    number: 175,
    type: "qcu",
    question: "Dans la phase Build, les risques incluent :",
    options: [
      "A. Uniquement les bugs visuels",
      "B. Injection de dépendances vulnérables, compromission de l'environnement, perte d'intégrité",
      "C. Uniquement les fautes d'orthographe",
      "D. Aucun risque",
    ],
    answers: ["B"],
  },
  {
    number: 176,
    type: "qcu",
    question: "La traçabilité entre le code source et le binaire produit est assurée par :",
    options: [
      "A. Aucun mécanisme",
      "B. Attestations de provenance et builds reproductibles",
      "C. Des captures d'écran",
      "D. Des emails",
    ],
    answers: ["B"],
  },
  {
    number: 177,
    type: "qcu",
    question: "Les attaques récentes sur la supply chain montrent que :",
    options: [
      "A. Le code interne suffit",
      "B. Même un code parfait peut être vulnérable via des dépendances compromises",
      "C. Les dépendances ne sont jamais un problème",
      "D. La sécurité n'est pas importante",
    ],
    answers: ["B"],
  },
  {
    number: 178,
    type: "qcu",
    question: "Un SBOM doit inclure :",
    options: [
      "A. Uniquement le nom de l'application",
      "B. Composants, dépendances directes, transitives, versions, origines, licences",
      "C. Uniquement les logos",
      "D. Uniquement le prix",
    ],
    answers: ["B"],
  },
  {
    number: 179,
    type: "qcu",
    question: "Lorsqu'une vulnérabilité critique est publiée, le SBOM permet de :",
    options: [
      "A. Ignorer le problème",
      "B. Identifier rapidement si l'application est concernée",
      "C. Supprimer l'application",
      "D. Rien du tout",
    ],
    answers: ["B"],
  },
  {
    number: 180,
    type: "qcu",
    question: "La signature des artefacts empêche :",
    options: [
      "A. La compilation",
      "B. L'exécution d'artefacts non approuvés ou corrompus",
      "C. Le développement",
      "D. La documentation",
    ],
    answers: ["B"],
  },
  {
    number: 181,
    type: "qcu",
    question: "Les builds reproductibles éliminent :",
    options: [
      "A. Tous les bugs",
      "B. Les variations artificielles (timestamps, données aléatoires)",
      "C. Les commentaires dans le code",
      "D. Les fonctionnalités",
    ],
    answers: ["B"],
  },
  {
    number: 182,
    type: "qcu",
    question: "Pour obtenir un build reproductible, il faut :",
    options: [
      "A. Changer constamment l'environnement",
      "B. Standardiser l'environnement et figer les versions de toutes les dépendances",
      "C. Utiliser des dépendances aléatoires",
      "D. Ne jamais documenter",
    ],
    answers: ["B"],
  },
  {
    number: 183,
    type: "qcu",
    question: "Dans un rapport DAST ZAP, une alerte 'Medium' signifie :",
    options: [
      "A. Aucun problème",
      "B. Une vulnérabilité de sévérité moyenne nécessitant attention",
      "C. Une fonctionnalité",
      "D. Un succès",
    ],
    answers: ["B"],
  },
  {
    number: 184,
    type: "qcu",
    question: "OWASP ZAP peut détecter :",
    options: [
      "A. Uniquement les erreurs de syntaxe",
      "B. SQL Injection, XSS, configurations faibles, etc.",
      "C. Uniquement les problèmes de design",
      "D. Les fautes d'orthographe",
    ],
    answers: ["B"],
  },
  {
    number: 185,
    type: "qcu",
    question: "Le mode de scan 'Active' dans ZAP :",
    options: [
      "A. Ne fait qu'observer",
      "B. Envoie des requêtes malveillantes pour tester les vulnérabilités",
      "C. Arrête l'application",
      "D. Ne fait rien",
    ],
    answers: ["B"],
  },
  {
    number: 186,
    type: "qcu",
    question: "Un fichier docker-compose.yml permet de :",
    options: [
      "A. Écrire du code Python",
      "B. Définir et orchestrer plusieurs conteneurs Docker",
      "C. Créer des présentations",
      "D. Éditer des images",
    ],
    answers: ["B"],
  },
  {
    number: 187,
    type: "qcu",
    question: "La commande 'docker-compose up -d' fait quoi ?",
    options: [
      "A. Supprime tous les conteneurs",
      "B. Démarre les conteneurs en arrière-plan (detached mode)",
      "C. Compile du code",
      "D. Installe Windows",
    ],
    answers: ["B"],
  },
  {
    number: 188,
    type: "qcu",
    question: "Dans un pipeline Jenkins, les rapports sont archivés pour :",
    options: [
      "A. Être supprimés immédiatement",
      "B. Consultation, traçabilité et audit",
      "C. Aucune raison",
      "D. Ralentir le système",
    ],
    answers: ["B"],
  },
  {
    number: 189,
    type: "qcu",
    question: "La normalisation des logs dans un SIEM vise à :",
    options: [
      "A. Supprimer les logs",
      "B. Unifier les formats pour faciliter l'analyse et la corrélation",
      "C. Augmenter la taille des fichiers",
      "D. Rendre les logs illisibles",
    ],
    answers: ["B"],
  },
  {
    number: 190,
    type: "qcu",
    question: "Un dashboard SIEM permet de :",
    options: [
      "A. Écrire du code",
      "B. Visualiser graphiquement l'activité et l'état de la sécurité",
      "C. Compiler des programmes",
      "D. Jouer à des jeux",
    ],
    answers: ["B"],
  },
  {
    number: 191,
    type: "qcu",
    question: "Le retour vers DevSecOps depuis le SIEM signifie :",
    options: [
      "A. Ignorer les incidents",
      "B. Utiliser les informations collectées pour améliorer les phases amont (exigences, modèle de menace)",
      "C. Ne rien faire",
      "D. Supprimer les données",
    ],
    answers: ["B"],
  },
  {
    number: 192,
    type: "qcu",
    question: "L'analyse forensique dans un SIEM permet de :",
    options: [
      "A. Prévenir tous les incidents futurs",
      "B. Reconstruire un incident à partir des événements collectés",
      "C. Supprimer les preuves",
      "D. Accélérer le réseau",
    ],
    answers: ["B"],
  },
  {
    number: 193,
    type: "qcu",
    question: "La conservation et l'archivage des logs sont importants pour :",
    options: [
      "A. Occuper de l'espace disque",
      "B. Audit, conformité réglementaire et enquêtes",
      "C. Ralentir le système",
      "D. Aucune raison",
    ],
    answers: ["B"],
  },
  {
    number: 194,
    type: "qcu",
    question: "L'approche multicouche ou défense en profondeur est recommandée par :",
    options: [
      "A. Aucune norme",
      "B. ISO/IEC 27002 et référentiels DGSSI",
      "C. Uniquement des blogs personnels",
      "D. Des forums non officiels",
    ],
    answers: ["B"],
  },
  {
    number: 195,
    type: "qcu",
    question: "Les exigences de sécurité doivent couvrir :",
    options: [
      "A. Uniquement le code",
      "B. Protection des données, contrôle d'accès, gestion des identités, journalisation, sécurité des communications",
      "C. Uniquement l'interface graphique",
      "D. Uniquement les performances",
    ],
    answers: ["B"],
  },
  {
    number: 196,
    type: "qcu",
    question: "Le chiffrement des données doit être appliqué :",
    options: [
      "A. Jamais",
      "B. Au repos et en transit",
      "C. Uniquement au repos",
      "D. Uniquement en transit",
    ],
    answers: ["B"],
  },
  {
    number: 197,
    type: "qcu",
    question: "La validation des entrées vise à prévenir :",
    options: [
      "A. Les performances optimales",
      "B. Injections SQL, XSS, commandes OS",
      "C. La documentation",
      "D. Les sauvegardes",
    ],
    answers: ["B"],
  },
  {
    number: 198,
    type: "qcu",
    question: "La gestion correcte des exceptions empêche :",
    options: [
      "A. L'exécution du code",
      "B. La divulgation d'informations techniques sensibles",
      "C. La compilation",
      "D. Le développement",
    ],
    answers: ["B"],
  },
  {
    number: 199,
    type: "qcu",
    question: "L'extraction de caractéristiques dans un IDS ML vise à :",
    options: [
      "A. Augmenter le bruit",
      "B. Transformer le bruit réseau en features exploitables et traçables",
      "C. Supprimer toutes les données",
      "D. Ralentir l'analyse",
    ],
    answers: ["B"],
  },
  {
    number: 200,
    type: "qcu",
    question: "La sécurité des systèmes d'information est :",
    options: [
      "A. Un état figé une fois mis en place",
      "B. Un processus continu de surveillance, évaluation et adaptation",
      "C. Une dépense inutile",
      "D. Uniquement la responsabilité du RSSI",
    ],
    answers: ["B"],
  },
];